### PR TITLE
WIP. pj-77-validate-html

### PR DESCRIPTION
**Pull request by NykoEugen**
I make func for sanitize htm, separet it works well. But in view I can't reach expected result. I tried take request data, change it and return in form, but somthing wrong,

### CODE REVIEW

**Comment by NykoEugen** [comment]
I think data changed in our form. And how change allowed_tags in form or models(ckeditor) I don't find

**Comment by NykoEugen** [comment]
The problem is probably that the text entered through the form is automatically escaped by Django when outputted in the template.

**Comment by NykoEugen** [comment]
Have a problem with lint, on my pc all tests are complete.

**Comment by acman** [comment]
I will check

**Pull request merged**
