### PR TITLE
WIP. pj-96-rework-comment-page

### PR DESCRIPTION
**Pull request by NykoEugen**
Change view post detail view. Need help with, how can I do that ckick on button answer, opened a answer form under comment?

### CODE REVIEW

**Comment by acman** [comment]
> Change view post detail view. Need help with, how can I do that ckick on button answer, opened a answer form under comment?

it is not required for now
u can just move to form on the bottom using id. Add id to form id="comment-form" and add link to button answer like post/my_post?#comment-form
and place comment text in form

**Comment by NykoEugen** [comment]
Done form for answer, but don't know why is style of form default

**Comment by NykoEugen** [comment]
Now the database changes the record instead of creating a new one when we update posts and comments, I changed the templates a little

**Comment by NykoEugen** [comment]
need make migration

**Review by acman — APPROVED** [review]
👍

**Pull request merged**
