### PR TITLE
pj-83 and pj-124 Ability to like and unlike post

### PR DESCRIPTION
**Pull request by Nikita88575**
Screenshot at 2024-02-06 22-42-23

### CODE REVIEW

**Comment by Nikita88575** [comment]
Screenshot at 2024-02-06 23-20-07
Screenshot at 2024-02-06 23-19-35

**Comment by Nikita88575** [comment]
Screenshots from another account
Screenshot at 2024-02-06 23-51-03
Screenshot at 2024-02-06 23-38-40

**Review by acman — CHANGES_REQUESTED** [review]
Great! look at get_context_data or something like this to avoid dublication and add tests

**Review by acman — APPROVED** [review]
LGTM!

**Pull request merged**
